
[package]
name = "isit-macros"
version = "0.1.1"
description = "Library for compile time assertions and conditional checks."
authors = ["ErisianArchitect <https://github.com/ErisianArchitect>"]
edition = "2024"
documentation = "https://docs.rs/isit/"
repository = "https://github.com/ErisianArchitect/isit"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.117"
proc-macro2 = "1.0.106"
quote = "1.0.45"
paste = "1.0.15"
proc-macro-crate = "3.5.0"
